[2025-05-05T23:44:41.174+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-05T23:44:41.194+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_sequential_run.dbt_deps manual__2025-05-05T23:39:36.223369+00:00 [queued]>
[2025-05-05T23:44:41.205+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_sequential_run.dbt_deps manual__2025-05-05T23:39:36.223369+00:00 [queued]>
[2025-05-05T23:44:41.210+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-05-05T23:44:41.233+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_deps> on 2025-05-05 23:39:36.223369+00:00
[2025-05-05T23:44:41.247+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_sequential_run', 'dbt_deps', 'manual__2025-05-05T23:39:36.223369+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dbt_run_dag.py', '--cfg-path', '/tmp/tmpn2qfqrjt']
[2025-05-05T23:44:41.252+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask dbt_deps
[2025-05-05T23:44:41.252+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=813) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-05T23:44:41.255+0000] {standard_task_runner.py:72} INFO - Started process 814 to run task
[2025-05-05T23:44:41.303+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_sequential_run.dbt_deps manual__2025-05-05T23:39:36.223369+00:00 [running]> on host 5f6a5c55bc08
[2025-05-05T23:44:41.355+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_sequential_run' AIRFLOW_CTX_TASK_ID='dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T23:39:36.223369+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T23:39:36.223369+00:00'
[2025-05-05T23:44:41.356+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-05T23:44:41.368+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-05T23:44:41.369+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt deps --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2025-05-05T23:44:41.375+0000] {subprocess.py:86} INFO - Output:
[2025-05-05T23:44:43.426+0000] {subprocess.py:93} INFO - [0m23:44:43  Running with dbt=1.8.7
[2025-05-05T23:44:43.675+0000] {subprocess.py:93} INFO - [0m23:44:43  Warning: No packages were found in packages.yml
[2025-05-05T23:44:43.694+0000] {subprocess.py:93} INFO - [0m23:44:43  Warning: No packages were found in packages.yml
[2025-05-05T23:44:44.296+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-05T23:44:44.321+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-05T23:44:44.322+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dbt_sequential_run, task_id=dbt_deps, run_id=manual__2025-05-05T23:39:36.223369+00:00, execution_date=20250505T233936, start_date=20250505T234441, end_date=20250505T234444
[2025-05-05T23:44:44.365+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-05T23:44:44.396+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-05T23:44:44.410+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
